### ISSUE TITLE
Hvilket test-rammeverk skal vi bruke?

### ISSUE THREAD

**Issue by olereidar** [olereidar/email-conjecture#1]
Hei! Jeg har bare litt erfaring med unit-testing i Java. Det eneste rammeverket jeg har brukt heter JUnit, et open-source test-rammeverk. Dette fungerer veldig godt med Maven og Mockito. 
Jeg er åpent for andre rammeverk dersom dere har noen preferanser.

[Slik får man tak på JUnit ved Maven](
https://github.com/junit-team/junit4/wiki/Download-and-Install)

**Comment by olereidar** [comment]
Siden ingen svarer, så får vi bare kjøre på da.

**Comment by jorjoh** [comment]
Har prøvd litt https://travis-ci.org/, men JUnit  er sikkert like greit

**Comment by olereidar** [comment]
JUnit er enhetstesting for å sjekke om Java-koden oppfører seg som forventet. Er travis for enhetstesting?
Kan se litt på det 💯

**Comment by jorjoh** [comment]
Når jeg brukte det, testet vi for eksempel om antall routes stemte overens med koden

**Comment by olereidar** [comment]
Høres bra ut, det er ikke det samme som JUnit 👍 
Spør igjen, kan du sette opp Travis? Har du noe erfaring med detta?

**Comment by jorjoh** [comment]
Okey, dette verktøyet er mest bruk i sammenheng med continuous integration, men er litt kult :)
![image](https://user-images.githubusercontent.com/8746948/29790572-9ae75dc0-8c3a-11e7-95e4-4518d8445f1d.png)
1. legg til brukernavn som i git
2. bruk token fra account på TravisCI
3. Merge relese med master branch

**Comment by olereidar** [comment]
Fikset.
