### ISSUE TITLE
Kan man ha spesialtegn i e-post domene?

### ISSUE THREAD

**Issue by olereidar** [olereidar/email-conjecture#16]
Kan man ha andre ting enn "." i e-post domene?
For eksempel:
...@selskap_selskap.com
...@selskap-selskap.com

eller er det kun "." som er lov?
...@selskap.selskap.com

**Comment by ERR0000RR** [comment]
Har prøvd å søke litt på domeneshop på forskjellige domener med .net .com .no og ut fra det jeg kan finne der, så ser det ut som at det er punktum og bindestrek bare som er lov!

**Comment by olereidar** [comment]
Da bør det være mulig å kutte ned på antallet e-poster som genereres. :-)
